# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import QMainWindow, QApplication
from ui_sign_up import Ui_SignUpWindow
# from ui_admin_dashboard import Ui_Admin_dashboard
from questions import Ui_Questions
from PyQt5 import QtWidgets, uic
import mysql.connector
from mysql.connector import connection, errorcode
from faculty_dashboard import Ui_Admin_dashboard
flag = True

# class MainWindow(object):
#     def __init__(self):
#         object.__init__(self)
#         self.ui = Ui_Questions()
#         self.ui.setupUi(self)

class Ui_Sign_In_Window(object):
    def setupUi(self, Sign_In_Window):
        Sign_In_Window.setObjectName("Sign_In_Window")
        Sign_In_Window.setEnabled(True)
        Sign_In_Window.setFixedSize(1200, 720)
        self.centralwidget = QtWidgets.QWidget(Sign_In_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -20, 1211, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/study_online.jpg"))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(700, 0, 500, 720))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color: rgba(0,0,0,100)")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(130, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.label_2.setObjectName("label_2")
        self.userName = QtWidgets.QLineEdit(self.widget)
        self.userName.setGeometry(QtCore.QRect(120, 200, 211, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.userName.setFont(font)
        self.userName.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(118, 125, 142, 160);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.userName.setObjectName("userName")
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(120, 300, 211, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(108, 120, 132, 160);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.signIn = QtWidgets.QPushButton(self.widget)
        self.signIn.setGeometry(QtCore.QRect(170, 460, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.signIn.setFont(font)
        self.signIn.setStyleSheet("QPushButton#signIn{\n"
"border-radius:5px;\n"
"color:rgba(255, 255, 255, 210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}\n"
"QPushButton#signIn:hover{\n"
"background-color:  qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(40, 671, 99, 215), stop:1 rgba(170, 85, 255, 255));\n"
"}\n"
"QPushButton#singIn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.signIn.setObjectName("signIn")
        self.signIn.clicked.connect(self.call_dashboard)
        self.toggleStudent = QtWidgets.QPushButton(self.widget)
        self.toggleStudent.setGeometry(QtCore.QRect(240, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toggleStudent.setFont(font)
        self.toggleStudent.setStyleSheet("background-color: rgb(178, 85, 245);\n"
"border-radius:5px;")
        self.toggleStudent.setObjectName("toggleStudent")

        self.toggleStudent.clicked.connect(self.progress)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(96, 393, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.label_3.setObjectName("label_3")
        self.signUp = QtWidgets.QPushButton(self.widget)
        self.signUp.setGeometry(QtCore.QRect(260, 390, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.signUp.setFont(font)
        self.signUp.setStyleSheet("QPushButton#signUp{\n"
"border-radius:5px;\n"
"color:rgba(255, 255, 255, 210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(20, 47, 78, 220), stop:1 rgba(85, 98, 112, 226));\n"
"}\n"
"QPushButton#signUp:hover{\n"
"background-color:  qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(40, 671, 99, 215), stop:1 rgba(105, 118, 132, 226));\n"
"}\n"
"QPushButton#signUo:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(105, 118, 132, 200);\n"
"}")
        self.signUp.setObjectName("signUp")
        self.signUp.clicked.connect(self.signup)
        self.signUp.clicked.connect(Sign_In_Window.hide)
        Sign_In_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Sign_In_Window)
        QtCore.QMetaObject.connectSlotsByName(Sign_In_Window)

    def retranslateUi(self, Sign_In_Window):
        _translate = QtCore.QCoreApplication.translate
        Sign_In_Window.setWindowTitle(_translate("Sign_In_Window", "MainWindow"))
        self.label_2.setText(_translate("Sign_In_Window", "Sign In as"))
        self.userName.setPlaceholderText(_translate("Sign_In_Window", "User Name"))
        self.password.setPlaceholderText(_translate("Sign_In_Window", "Password"))
        self.signIn.setText(_translate("Sign_In_Window", "Sign In"))
        self.toggleStudent.setText(_translate("Sign_In_Window", "Student"))
        self.label_3.setText(_translate("Sign_In_Window", "Don\'t have account?"))
        self.signUp.setText(_translate("Sign_In_Window", "Sign Up"))

    def progress(self):
        global flag
        if flag:
                flag = False
                self.toggleStudent.setText('Teacher')
                
        else:
                flag = True
                self.toggleStudent.setText('Student')
    def signup(self):
        self.signupwindow = QtWidgets.QMainWindow()
        self.ui = Ui_SignUpWindow()
        self.ui.setupUi(self.signupwindow)
        
        self.signupwindow.show()

    def call_dashboard(self):
        try:
                mydb = connection.MySQLConnection(
        database = 'online_examination_system',
        host = '127.0.0.1',
        user = "root",
        password = "HSbF6@123$"
)
        except mysql.connector.Error as err:
                if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
                        print("Wrong username or password")
                if err.errno == errorcode.ER_BAD_DB_ERROR:
                        print("Database does not exist")
                else:
                        print(err)
        text_username = str(self.userName.text())
        text_password = str(self.password.text())

        if flag:
                access_db = ("SELECT username, password FROM student_table")
        else:
                access_db = ("SELECT username, password FROM faculty_table")
        cursor = mydb.cursor()
        cursor.execute(access_db)

        for x in cursor.fetchall():
                if x[0] == text_username and x[1] == text_password:

                        self.dashboard = QtWidgets.QMainWindow() 
                        self.ui = Ui_Admin_dashboard()
                        self.ui.setupUi(self.dashboard)
                        self.dashboard.show()
                        

                        # self.quest = QtWidgets.QMainWindow()
                        # self.ui = Ui_Questions()
                        # self.ui.setupUi(self.quest)
                        # self.quest.show()

                        # self.main = MainWindow()
                        # self.main.show()
                        # self.close()
                        break
                else:
                        print ("Wrong username or password!!!")
                        break