# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
import random
import smtplib
import mysql.connector
from mysql.connector import connection, errorcode
# from ui_sign_in import Ui_Sign_In_Window

flag = True
# server_password = 'wzgreexzxwzapkcj'
otp = ""
class Ui_SignUpWindow(object):
    def setupUi(self, SignUpWindow):
        SignUpWindow.setObjectName("SignUpWindow")
        SignUpWindow.setFixedSize(1200, 720)
        self.centralwidget = QtWidgets.QWidget(SignUpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1200, 720))
        self.frame.setStyleSheet("background-color:rgba(0,0,0,100);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(600, 0, 600, 720))
        self.widget.setStyleSheet("QWidget#widget{\n"
"border-radius:5px;\n"
"color:rgba(255, 255, 255, 210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(40, 67, 98, 220), stop:1 rgba(105, 118, 132, 226));\n"
"}")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(80, 90, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(280, 90, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(149, 20, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.firstName = QtWidgets.QLineEdit(self.widget)
        self.firstName.setGeometry(QtCore.QRect(80, 120, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.firstName.setFont(font)
        self.firstName.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(138, 155, 162, 180);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.firstName.setObjectName("firstName")
        self.lastName = QtWidgets.QLineEdit(self.widget)
        self.lastName.setGeometry(QtCore.QRect(280, 120, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lastName.setFont(font)
        self.lastName.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(138, 155, 162, 180);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.lastName.setObjectName("lastName")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(80, 270, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.label_7.setObjectName("label_7")
        self.email = QtWidgets.QLineEdit(self.widget)
        self.email.setGeometry(QtCore.QRect(80, 300, 370, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(138, 155, 162, 180);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(80, 390, 370, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(138, 155, 162, 180);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.confirmedPassword = QtWidgets.QLineEdit(self.widget)
        self.confirmedPassword.setGeometry(QtCore.QRect(80, 480, 370, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.confirmedPassword.setFont(font)
        self.confirmedPassword.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(138, 155, 162, 180);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.confirmedPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmedPassword.setObjectName("confirmedPassword")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(80, 360, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(80, 450, 141, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.label_9.setObjectName("label_9")
        self.error_msg = QtWidgets.QLabel(self.widget)
        self.error_msg.setGeometry(QtCore.QRect(80, 520, 160, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.error_msg.setFont(font)
        self.error_msg.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.error_msg.setObjectName("error_msg")
        self.sign_up = QtWidgets.QPushButton(self.widget)
        self.sign_up.setGeometry(QtCore.QRect(230, 640, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sign_up.setFont(font)
        self.sign_up.setStyleSheet("QPushButton#sign_up{\n"
"border-radius:5px;\n"
"color:rgba(255, 255, 255, 210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}")
        self.sign_up.setObjectName("sign_up")
        self.sign_up.clicked.connect(self.storeTo_db)
        self.generateOTP = QtWidgets.QPushButton(self.widget)
        self.generateOTP.setGeometry(QtCore.QRect(290, 550, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.generateOTP.setFont(font)
        self.generateOTP.setStyleSheet("QPushButton#generateOTP{\n"
"border-radius:5px;\n"
"color:rgba(255, 255, 255, 210);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(20, 47, 78, 220), stop:1 rgba(75, 98, 212, 226));\n"
"}")
        self.generateOTP.setObjectName("generateOTP")
        self.generateOTP.clicked.connect(self.generatingOTP)
        self.generatedOTP = QtWidgets.QLineEdit(self.widget)
        self.generatedOTP.setGeometry(QtCore.QRect(90, 550, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.generatedOTP.setFont(font)
        self.generatedOTP.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(138, 155, 162, 180);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.generatedOTP.setObjectName("generatedOTP")

        self.toggle_sign_up = QtWidgets.QPushButton(self.widget)
        self.toggle_sign_up.setGeometry(QtCore.QRect(240, 20, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.toggle_sign_up.setFont(font)
        self.toggle_sign_up.setStyleSheet("background-color: rgb(178, 85, 245);\n"
"border-radius:5px;")
        self.toggle_sign_up.setObjectName("toggle_sign_up")
        self.toggle_sign_up.clicked.connect(self.toggle_signup)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setGeometry(QtCore.QRect(80, 180, 90, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"color:rgba(255, 255, 255, 230);\n"
"")
        self.label_16.setObjectName("label_16")
        self.userName = QtWidgets.QLineEdit(self.widget)
        self.userName.setGeometry(QtCore.QRect(80, 220, 370, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.userName.setFont(font)
        self.userName.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(138, 155, 162, 180);\n"
"color:rgba(255, 255, 255, 230);\n"
"padding-bottom:7px;")
        self.userName.setObjectName("userName")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-10, -20, 1211, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/study_online.jpg"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.widget.raise_()
        SignUpWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SignUpWindow)
        QtCore.QMetaObject.connectSlotsByName(SignUpWindow)

    def retranslateUi(self, SignUpWindow):
        _translate = QtCore.QCoreApplication.translate
        SignUpWindow.setWindowTitle(_translate("SignUpWindow", "MainWindow"))
        self.label_4.setText(_translate("SignUpWindow", "First Name"))
        self.label_5.setText(_translate("SignUpWindow", "Last Name"))
        self.label_6.setText(_translate("SignUpWindow", "Sign Up as"))
        self.label_7.setText(_translate("SignUpWindow", "Email"))
        self.label_8.setText(_translate("SignUpWindow", "Password"))
        self.label_9.setText(_translate("SignUpWindow", "Confirm Password"))
        self.sign_up.setText(_translate("SignUpWindow", "Sign Up"))
        self.generateOTP.setText(_translate("SignUpWindow", "Generate OTP"))
        self.toggle_sign_up.setText(_translate("SignUpWindow", "Student"))
        self.label_16.setText(_translate("SignUpWindow", "Username"))

    def toggle_signup(self):
        global flag
        if flag:
                flag = False
                self.toggle_sign_up.setText('Teacher')
        else:
                flag = True
                self.toggle_sign_up.setText('Student')

    def generatingOTP(self):
        global otp
        email_id = str(self.email.text())
        # global server_password
        server = smtplib.SMTP('smtp.gmail.com', port=587)
        server.starttls()
        otp = ''.join([str(random.randint(0,9)) for i in range(6)])
        server.login('abhaymaurya811@gmail.com', 'hzfpcnmwtjhivpmr')
        msg = 'Hello, Your OTP is ' + str(otp)
        server.sendmail('abhaymaurya811@gmail.com', email_id, msg)
        server.quit()

    def storeTo_db(self):
        global otp
        print(otp)
        try:
                mydb = connection.MySQLConnection(
        database = 'online_examination_system',
        host = '127.0.0.1',
        user = "root",
        password = "HSbF6@123$"
)
        except mysql.connector.Error as err:
                if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
                        print("Wrong username or password")
                if err.errno == errorcode.ER_BAD_DB_ERROR:
                        print("Database does not exist")
                else:
                        print(err)

        first_name = str(self.firstName.text())
        last_name = str(self.lastName.text())
        user_name = str(self.userName.text())
        email_id = str(self.email.text())
        user_password = str(self.password.text())
        user_confirmed_password = str(self.confirmedPassword.text())
        user_otp = str(self.generatedOTP.text())

        if flag:
                add_user = ("INSERT INTO student_table (username, first_name, last_name, email_id, password) VALUES (%s, %s, %s, %s, %s)")
        else:
                add_user = ("INSERT INTO faculty_table (username, first_name, last_name, email_id, password) VALUES (%s, %s, %s, %s, %s)")
        user_data = (user_name, first_name, last_name, email_id, user_password)
        cursor = mydb.cursor()
        if user_password == user_confirmed_password and user_otp == otp:
                cursor.execute(add_user, user_data)
                mydb.commit()
                
        else:
                print("Password or otp doesn't match!!!")
                self.error_msg.setText('Password does not match')
                self.error_msg.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border: none;\n"
"color:rgba(255, 0, 0, 230);\n"
"")
        cursor.close()
        mydb.close()
        # self.signinwindow = QtWidgets.QMainWindow()
        # self.ui = Ui_Sign_In_Window
        # self.ui.setupUi(self.signinwindow)
        # self.signinwindow.show()